version: "3.8"

services:
  redis:
    image: redis:7
    restart: always
    volumes:
      - redis:/data

  db:
    image: postgres:15
    restart: always
    environment:
      - POSTGRES_DB=${POSTGRES_DB:-superset}
      - POSTGRES_USER=${POSTGRES_USER:-superset}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-superset}
    volumes:
      - db_home:/var/lib/postgresql/data

  superset:
    image: apache/superset:latest
    restart: always
    ports:
      - "${PORT:-8088}:8088"
    depends_on:
      - db
      - redis
    environment:
      SUPERSET_SECRET_KEY: ${SUPERSET_SECRET_KEY}
      DATABASE_URL: postgresql://${POSTGRES_USER:-superset}:${POSTGRES_PASSWORD:-superset}@db/${POSTGRES_DB:-superset}
      REDIS_URL: redis://redis:6379/0
    volumes:
      - superset_home:/app/superset_home
    entrypoint: ["/usr/bin/docker-entrypoint.sh"]
    command: ["flask", "run", "-p", "8088", "--host=0.0.0.0"]

volumes:
  superset_home:
  db_home:
  redis:
